version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"  # Define the web entrypoint
      - "--entrypoints.websecure.address=:443"  # Define the websecure entrypoint
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend1:
    image: nginx:alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend1.rule=Host(`backend1.localhost`)"
      - "traefik.http.routers.backend1.entrypoints=web"
      - "traefik.http.services.backend1.loadbalancer.server.port=80" # backend container port
      - "traefik.http.middlewares.backend1-redirect.redirectscheme.scheme=http"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html

  backend2:
    image: httpd:alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend2.rule=Host(`backend2.localhost`)"
      - "traefik.http.routers.backend2.entrypoints=web"
      - "traefik.http.services.backend2.loadbalancer.server.port=80" # backend container port
      - "traefik.http.middlewares.backend2-redirect.redirectscheme.scheme=http"
    volumes:
      - ./index2.html:/usr/local/apache2/htdocs/index.html
